version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - go-network

  go-gin-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: go_gin_api
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8080:8080"
    networks:
      - go-network

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: go_app
    depends_on:
      - go-gin-api
    ports:
      - "8081:8081"
    networks:
      - go-network

networks:
  go-network:
    driver: bridge

volumes:
  postgres_data:
